AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda data getter implementation for periodic execution

Parameters:
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 512
  Entrypoint:
    Type: String
    Default: com.data-getter.core
  StageName:
    Type: String
    Default: data-getter

Globals:
  Function:
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize
    Environment:
      Variables:
        HL_ENTRYPOINT: !Ref Entrypoint

Resources:
  DataGetterLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DataGetterLambdaFunction
      PackageType: Image
      Events:
        HelloEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref BotHttpApi
            Path: /
            Method: GET
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1

  BotHttpApi:
    Type: AWS::Serverless::HttpApi
    DeletionPolicy: Retain
    Properties:
      StageName: !Ref StageName

Outputs:
  DataGetterLambdaEndpoint:
    Description: Endpoint for DataGetterLambdaFunction
    Value:
      Fn::Sub: https://${BotHttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/
